[project]
name = "gg_custom"
authors = [
    { name = "Libermatic LLP", email = "info@libermatic.com"}
]
description = "Customizations for GG"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
black = "==20.8b1"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
typing-modules = ["frappe.types.DF"]
